# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://impactinasia.co
title: Impact in Asia
email: impactinasia@gmail.com
author: Impact in Asia
slogan: How Asia is making a difference
description: > # "Write an awesome description for your new site here. 
 How Asia is making a difference. Join now to make a difference.
favicon: logo_iia.png
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

baseurl: /impactinasia

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/impactinasia
  - title: facebook
    url: http://facebook.com/ImpactInAsia

# ----------------------- #

# ----------------------- #
#  Type of actors         #
# ----------------------- #

actors:
  - title: user
    label: individual
    url:  http://goo.gl/forms/TEPAC7Rcqz
  - title: group
    label: organization
    url: http://goo.gl/forms/6Y71FxjnDB 

services:
  - title: newspaper-o
    label: inspire
    url: \#inspire
  - title: cogs
    label: connect
    url: \#connect
  - title: play 
    label: take action 
    url: \#act

