# Site wide configuration

title: Impact In Asia
description: Impact in Asia connects people who want to make a difference and have a positive impact in Asia.
logo: impact_in_asia_120x120.png # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: #http://www.impactinasia.co

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Impact in Asia
  email: impactinasia@gmail.com
  twitter: https://twitter.com/impactinasia
  google:
    ad-client:
    ad-slot:
  bio: We connect those who want to make a difference in Asia and turn connections into actions. 
  avatar: impact_in_asia_160x160.png # 160x160 px image for author byline
  disqus-shortname:
  web: www.impactinasia.co


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
